### ISSUE TITLE
C# without anchor

### ISSUE THREAD

**Issue by felipemfp** [IonicaBizau/made-in-romania#2]
In **Contents** you have `[C#](undefined)` and after **Java**, I believe it's *C#*, but we see only *C* (so we have two *C* sections).

**Comment by IonicaBizau** [comment]
@felipemfp That's a good point indeed. There is a script which is still updating the data for different languages. I'm trying to fix it while this is running. Hopefully it will be fine. 😂

**Comment by IonicaBizau** [comment]
In the mean time, can you search for a fix how to display `#` in the heading?

If I do `## C#` it's not rendering it correctly:

## C#

**Comment by felipemfp** [comment]
You can add one extra space after that, e.g.: `## C# ` 
Or add one extra **#**, e.g.: `## C# #` 

## C# 

## C# #

**Comment by IonicaBizau** [comment]
Thanks a lot! Should be fixed now. Using the `## C# #` solution since my editor strips the trailing spaces. 😁

**Comment by IonicaBizau** [comment]
@felipemfp And here we got a list of nice projects made in Brazil. 😁 
—https://github.com/IonicaBizau/made-in-brazil
