### ISSUE TITLE
Rust category?

### ISSUE THREAD

**Issue by zakkor** [IonicaBizau/made-in-romania#21]

**Comment by IonicaBizau** [comment]
Contributions are welcome. 😀

**Comment by cdman** [comment]
@zakkor - you have some cool repos under your profile, would love to have them as part of made-in-romania! Just submit a PR.

**Comment by zakkor** [comment]
@cdman: I would love to be a part of this project, however, I'm not sure how it works. Should I edit `package.json` manually, adding a Rust category with my repos to it, and you guys generate the `readme.md`?

**Comment by IonicaBizau** [comment]
Yes, edit the package.json file following the existing content. It's not well documented but I will help you. 😀

**Comment by zakkor** [comment]
@IonicaBizau: Here it is: #22

**Comment by IonicaBizau** [comment]
Thanks! I'm traveling these days but I'll keep an eye on it. 🍀

**Comment by zakkor** [comment]
Thanks!
