### ISSUE TITLE
Language agnostic projects

### ISSUE THREAD

**Issue by vimishor** [IonicaBizau/made-in-romania#38]
I just wanted to ask what are your thoughts regarding language agnostic projects. 
Could a new category be created for them or you don't want them listed ?

I'm asking this because I work on a initial draft for [C.N.P.](https://github.com/vimishor/cnp-spec) specification and wished I could add it to this list.

**Comment by IonicaBizau** [comment]
Sure, definitely! ❇️ Feel free to contribute.

**Comment by vimishor** [comment]
Any ideas about the name of the new section ?

"_Specifications_" could be OK for this project in particular but maybe something more generic could be used instead, so other projects which have nothing to do with specifications could be added (_like open data, schemas, etc_).

**Comment by IonicaBizau** [comment]
Maybe *Language agnostic*. I'm open for suggestions.

**Comment by IonicaBizau** [comment]
@vimishor I'm closing this. If you have any ideas, feel free to open issues! Thank you for your contribution! ❇️
